name: Deploy CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v3
        with:
          cache-dependency-path: frontend/yarn.lock
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: |
          cd frontend
          yarn ci

      - run: |
          cd frontend
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
